name: 提交错误
description: 各种各样的奇怪的问题都可以提交。
body:
    - type: dropdown
      attributes:
          label: 错误来源
          options:
              - QQ Bot
              - All
              - Web
              - Electron
              - Tauri
              - Android
              - iOS/iPadOS
              - 其他
    - type: textarea
      attributes:
          label: 描述错误
          description: 发生了什么呢 …… 简单说一下就好了（x
      required: true
    - type: textarea
      attributes:
          label: 复现流程
          description: 如果你可以重现这个 BUG，你可以在下面留下操作流程
      required: true
    - type: textarea
      attributes:
          label: 截图
          description: 如果有附加的截图，可以添加在下面
    - type: textarea
      attributes:
          label: 版本信息
          description: 执行 “设置 - 高级 - 输出调试信息” 获取应用运行的版本信息，粘贴到这儿以方便快速了解运行环境
      required: true
    - type: textarea
      attributes:
          label: 更多
          description: 还有别的要说吗？比如说控制台的报错之类的，都可以塞这儿
