name: 功能请求
description: 有什么新的功能想法？欢迎提交。
body:
    - type: dropdown
      attributes:
          label: 适用版本
          options:
              - All
              - Web
              - Electron
              - Tauri
              - 其他
    - type: textarea
      attributes:
          label: 描述请求
          description: 你想要什么功能呢？简单说一下就好了（x
      required: true
    - type: textarea
      attributes:
          label: 截图
          description: 如果有附加的截图，可以添加在下面
