name: 构建 Docker

on:
  workflow_call:
    inputs:
      version:
        description: '应用版本'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4
      - name: 下载 Web 版本构建产物
        uses: actions/download-artifact@v4
        with:
            name: ${{ inputs.version }}-web
      - name: 解压 Web 版本构建产物
        run: unzip -q Stapxs.QQ.Lite-${{ inputs.version }}-web.zip
      - name: 登录 Docker Hub
        uses: docker/login-action@v2
        with:
          username: stapxs
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: 构建 Docker 镜像并推送
        run: |
            docker buildx create --use
            docker buildx build --platform linux/amd64,linux/arm64 -t stapxs/qq-web:latest --push .
