name: 构建 Web

on:
  workflow_call:
    inputs:
      version:
        description: '应用版本'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
            - name: 拉取代码
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: 设置 Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: 更新依赖
              run: yarn
            - name: 构建
              run: yarn build
            - name: 压缩构建产物
              run: zip -r Stapxs.QQ.Lite-${{ inputs.version }}-web.zip dist
            - name: 上传构建产物
              uses: actions/upload-artifact@v4
              with:
                  name: ${{ inputs.version }}-web
                  path: Stapxs.QQ.Lite-${{ inputs.version }}-web.zip
