name: lint
on:
    pull_request: # PR 触发
        branches:
            - next

jobs:
    lint:
        runs-on: ubuntu-22.04
        steps:
            - name: 安装构建依赖
              run: |
                sudo apt-get update
                sudo apt-get install -y libglib2.0-dev \
                                        libgtk-3-dev \
                                        pkg-config \
                                        xdg-utils \
                                        build-essential \
                                        librsvg2-dev \
                                        libwebkit2gtk-4.0-dev \
                                        libwebkit2gtk-4.1-dev \
                                        libjavascriptcoregtk-4.0-dev \
                                        libayatana-appindicator3-dev
            - name: 拉取代码
              uses: actions/checkout@v4
              with:
                  submodules: recursive
                  persist-credentials: false
            - name: 设置 Nodejs
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
            - name: 更新依赖
              run: yarn
            # 代码检查
            - name: Vue 代码检查
              run: yarn lint

            - name : Tauri 代码检查
              run: yarn lint:tauri
